version: "3.8"

services:
  app:
    container_name: h24s18_app

    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/go/app
    environment:
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: password
      MARIADB_HOSTNAME: db
      MARIADB_DATABASE: database
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    expose:
      - 3306
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 60

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql: