version: "3"

tasks:
  up:
    desc: up container 
    cmd: docker compose up -d
  down:
    desc: down concatiner
    cmd: docker compose down
  logs:
    desc: logs container
    cmd: docker compose logs -f